### ISSUE TITLE
Support more date formats

### ISSUE THREAD

**Issue by jocooler** [rina-andria/PowerBI-BrushChart#1]
I'm not exactly sure what date formats are supported, but I've tried:

MMMM dd, yyyy
mm/dd/yy
mm/dd/yyyy

And I keep getting the error "The Category Data should be a Date". Am I missing something?

**Comment by rina-andria** [comment]
hi, what kind of datasource do you use? It may come from the fact the date has the right string date format but not the right type.

**Comment by stevenlim817** [comment]
Hi, I am having the same issue. The data came from MySQL, and the type is set properly in the database. Please help! 

Thanks in advance!

**Comment by rina-andria** [comment]
hi, please check if the field type inside PBI desktop is a date, like in the screenshhot.

![image](https://cloud.githubusercontent.com/assets/6961719/16578861/18118656-429d-11e6-9f79-73be4e2b5278.png)
